### ISSUE TITLE
e2e tests failed

### ISSUE THREAD

**Issue by qw1mb0** [kubernetes/kube-state-metrics#771]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When I run e2e tests (`./tests/e2e.sh`), I get an error:
```
* Done! kubectl is now configured to use "minikube"
! minikube IP was already correctly configured for 192.168.99.102
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
docker run --rm -v "$PWD":/go/src/k8s.io/kube-state-metrics -w /go/src/k8s.io/kube-state-metrics -e GOOS=linux -e GOARCH=amd64 -e CGO_ENABLED=0 golang:1.12 go build -ldflags "-s -w -X k8s.io/kube-state-metrics/pkg/version.Release=v1.6.0 -X k8s.io/kube-state-metrics/pkg/version.Commit=9a8e234 -X k8s.io/kube-state-metrics/pkg/version.BuildDate=2019-05-28T12:34:41Z" -o kube-state-metrics
can't load package: package k8s.io/kube-state-metrics: no Go files in /go/src/k8s.io/kube-state-metrics
Makefile:84: recipe for target '.container-amd64' failed
make: *** [.container-amd64] Error 1
```

**What you expected to happen**:
All e2e tests complete.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- minikube version: `minikube version: v1.1.0`

- virtualbox version: `5.2.18_Ubuntu r123745`

- docker-machine version: `docker-machine version 0.16.0, build 702c267f`

**Comment by brancz** [comment]
where did you clone this repo into? sounds like you have it in `$GOPATH/src/github.com/kubernetes/kube-state-metrics` but it needs to be in `$GOPATH/src/k8s.io/kube-state-metrics`.

**Comment by qw1mb0** [comment]
I have a copy of the repository in `/home/user/kube-state-metrics`.

My `export GOPATH=/home/user/kube-state-metrics`, but e2e tests return the same error.

**Comment by brancz** [comment]
you need a real go path, modeled in the way as I described above, that's required by go :)

**Comment by qw1mb0** [comment]
I fixed the gopath and now it is such an:
```
# env | grep GOPATH
GOPATH=/home/user/go
```
I’m in the correct directory:
```
# pwd
/home/user/go/src/k8s.io/kube-state-metrics
```
But e2e tests continue to fall with the error:
```
* Done! kubectl is now configured to use "minikube"
! minikube IP was already correctly configured for 192.168.99.100
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
docker run --rm -v "$PWD":/go/src/k8s.io/kube-state-metrics -w /go/src/k8s.io/kube-state-metrics -e GOOS=linux -e GOARCH=amd64 -e CGO_ENABLED=0 golang:1.12 go build -ldflags "-s -w -X k8s.io/kube-state-metrics/pkg/version.Release=v1.6.0 -X k8s.io/kube-state-metrics/pkg/version.Commit=ce1bda0 -X k8s.io/kube-state-metrics/pkg/version.BuildDate=2019-05-29T16:13:08Z" -o kube-state-metrics
can't load package: package k8s.io/kube-state-metrics: no Go files in /go/src/k8s.io/kube-state-metrics
Makefile:84: recipe for target '.container-amd64' failed
make: *** [.container-amd64] Error 1
```

At the same time, manually launching `make container` works correctly:
```
docker run --rm -v "$PWD":/go/src/k8s.io/kube-state-metrics -w /go/src/k8s.io/kube-state-metrics -e GOOS=linux -e GOARCH=amd64 -e CGO_ENABLED=0 golang:1.12 go build -ldflags "-s -w -X k8s.io/kube-state-metrics/pkg/version.Release=v1.6.0 -X k8s.io/kube-state-metrics/pkg/version.Commit=ce1bda0 -X k8s.io/kube-state-metrics/pkg/version.BuildDate=2019-05-29T16:15:25Z" -o kube-state-metrics
cp -r * /tmp/tmp.771uhkN3Sr
docker build -t quay.io/coreos/kube-state-metrics-amd64:v1.6.0 /tmp/tmp.771uhkN3Sr
Sending build context to Docker daemon  53.73MB
Step 1/8 : FROM alpine:3.9
 ---> 055936d39205
Step 2/8 : RUN adduser -D kube-state-metrics
 ---> Using cache
 ---> 6a7541b1f3c9
Step 3/8 : FROM gcr.io/distroless/static
 ---> a574914f27fd
Step 4/8 : COPY kube-state-metrics /
 ---> f519f57d9e48
Step 5/8 : COPY --from=0 /etc/passwd /etc/passwd
 ---> 114e1da52d4b
Step 6/8 : USER kube-state-metrics
 ---> Running in 90fc3dcf18c2
Removing intermediate container 90fc3dcf18c2
 ---> a50c7f9c7b5b
Step 7/8 : ENTRYPOINT ["/kube-state-metrics", "--port=8080", "--telemetry-port=8081"]
 ---> Running in 903d5b5e50b7
Removing intermediate container 903d5b5e50b7
 ---> 4092a166dcec
Step 8/8 : EXPOSE 8080 8081
 ---> Running in bf6feee269f4
Removing intermediate container bf6feee269f4
 ---> 82f10d0ccc0f
Successfully built 82f10d0ccc0f
Successfully tagged quay.io/coreos/kube-state-metrics-amd64:v1.6.0
docker tag quay.io/coreos/kube-state-metrics-amd64:v1.6.0 quay.io/coreos/kube-state-metrics-amd64:latest
# Adding check for amd64
docker tag quay.io/coreos/kube-state-metrics-amd64:v1.6.0 quay.io/coreos/kube-state-metrics:v1.6.0
docker tag quay.io/coreos/kube-state-metrics-amd64:v1.6.0 quay.io/coreos/kube-state-metrics:latest
``

**Comment by brennerm** [comment]
IMO the issue comes from a bug in the `tests/e2e.sh`. If the MINIKUBE_DRIVER is not "none" the DOCKER_HOST is switched to the minikube VM.

`[[ "$MINIKUBE_DRIVER" != "none" ]] && eval "$(minikube docker-env)"`

`make container` tries to bind mount the source code from the path on the host machine which is ofc not available in the minikube VM.

`docker run --rm -v "/home/user/src/go/src/k8s.io/kube-state-metrics:/go/src/k8s.io/kube-state-metrics" ...`

**Comment by olivierlemasle** [comment]
I do not have the rights to /reopen this issue, but the issue persists.
As explained by @brennerm, the e2e failure occurs when `MINIKUBE_DRIVER` is not `none`.

In that case, `tests/e2e.sh` uses `eval "$(minikube docker-env)"`, so the docker engine used to build `kube-state-metrics` is the docker engine of the Minikube VM and the volume mounts is empty.

This issue is addresses by #1065.
